##services:
##  - type: web
##    name: virtual-try-on
##    runtime: python
##    buildCommand: pip install -r requirements.txt
##    startCommand: gunicorn run:app
##    envVars:
##      - key: DATABASE_URL
##        fromDatabase:
##          name: virtual_try_on_db
##          property: connectionString
##      - key: PYTHON_VERSION
##        value: 3.9.13
#
##services:
##  - type: web
##    name: virtual-try-on
##    runtime: python
##    buildCommand: |
##      pip install -r requirements.txt
##      python -m flask init-db
##    startCommand: gunicorn run:app  # Changed from 'app:app' to 'run:app'
##    envVars:
##      - key: DATABASE_URL
##        value: /opt/render/project/src  # Add this line
##
##        fromDatabase:
##          name: virtual_try_on_db
##          property: connectionString
##      - key: PYTHON_VERSION
##        value: 3.9.13
##
##databases:
##  - name: virtual_try_on_db
##    plan: free
#
#
#services:
#  - type: web
#    name: virtual-try-on
#    runtime: python
#    buildCommand: |
#      pip install -r requirements.txt
#      python -m flask init-db
#    startCommand: gunicorn run:app
#    envVars:
#      - key: DATABASE_URL
#        fromDatabase:
#          name: virtual_try_on_db
#          property: connectionString
#      - key: PYTHON_VERSION
#        value: 3.9.13
#
#databases:
#  - name: virtual_try_on_db
#    plan: free




services:
  - type: web
    name: virtual-try-on
    env: python
    region: virginia
    plan: free  # or standard for production
    buildCommand: pip install -r requirements.txt && mkdir -p Resources/shirts static/uploads static/processed  # Add this line
#    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/static/uploads
      - key: PROCESSED_FOLDER
        value: /opt/render/project/src/static/processed
#      - key: SHIRT_FOLDER
#        value: /var/data/Resources/shirts
      - key: SHIRT_FOLDER
        value: /opt/render/project/src/static/shirts
      - key: PYTHON_VERSION
        value: 3.10.13  # Match your runtime
    disk:
      name: app-data
      mountPath: /var/data
      sizeGB: 1

databases:
  - name: virtualtryon-db
    plan: free  # or starter/production for real usage
    region: virginia